site_name: European Digital Identity
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.top
    - navigation.footer
    - navigation.indexes
  logo: assets/logo_eudi_white.svg
  favicon: assets/favicon.ico

extra_css:
  - css/extra.css

markdown_extensions:
  - footnotes
  - sane_lists
  - tables
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

site_url: https://docs.eudi.dev
repo_url: https://github.com/eu-digital-identity-wallet/eudi-docs-site
repo_name: eu-digital-identity-wallet/eudi-docs-site

nav:
  - European Digital Identity Wallet: https://eudi.dev/latest/
  - Architecture and reference framework: https://eudi.dev/latest/architecture-and-reference-framework-main/
  - Discussion topics: https://eudi.dev/latest/discussion-topics/
  - Technical specifications: https://eudi.dev/latest/technical-specifications/
  - Reference Implementation:
      - Overview: 
          - Overview: index.md
          - Feature Map: reference-implementation/feature-map.md
          - Roadmap: reference-implementation/roadmap.md
          - Repositories: reference-implementation/repositories-list.md
          - Code Quality Assurance: reference-implementation/quality-assurance.md
      - Build:
          - Build: build/index.md
          - Build your Wallet:
              - Build your Wallet: build/build-your-wallet/index.md
              - Android:
                  - Wallet Application Level:
                      - Build the App: build/build-your-wallet/android/wallet-application-level/index.md
                      - Run with Remote Services: build/build-your-wallet/android/wallet-application-level/running-with-remote-services.md
                      - Run with Local Services: build/build-your-wallet/android/wallet-application-level/running-with-local-services.md
                      - Self-signed Certificates: build/build-your-wallet/android/wallet-application-level/self-signed-certificates.md
                  - Library Level:
                      - Introduction: build/build-your-wallet/android/library-level/index.md
                      - Build the Core: build/build-your-wallet/android/library-level/build-the-core.md
                      - Manage Documents: build/build-your-wallet/android/library-level/manage-documents.md
              - iOS:
                  - Wallet Application Level:
                      - Build the App: build/build-your-wallet/ios/wallet-application-level/index.md
                      - Run with Remote Services: build/build-your-wallet/ios/wallet-application-level/running-with-remote-services.md
                      - Run with Local Services: build/build-your-wallet/ios/wallet-application-level/running-with-local-services.md
                      - Self-signed Certificates: build/build-your-wallet/ios/wallet-application-level/self-signed-certificates.md
                  - Library Level:
                      - Introduction: build/build-your-wallet/ios/library-level/index.md
                      - Build the Kit: build/build-your-wallet/ios/library-level/build-the-kit.md
                      - Manage Documents: build/build-your-wallet/ios/library-level/manage-documents.md
          - Build your Issuer:
              - Overview: build/build-your-issuer/index.md
              - Steps to Build: build/build-your-issuer/steps-to-build.md
              - Configure your Issuer: build/build-your-issuer/configure.md
              - Add Attestations: build/build-your-issuer/new-attestation.md
          - Build your Remote Verifier:
              - Overview: build/build-your-remote-verifier/index.md
              - Steps to Build: build/build-your-remote-verifier/steps-to-build.md
              - Configure your Verifier: build/build-your-remote-verifier/configure.md 
          - Build your Proximity Verifier:
              - Overview: build/build-your-proximity-verifier/index.md
              - Build your Proximity Verifier App for Android: build/build-your-proximity-verifier/build-your-proximity-verifier-app-for-android.md
              - Build your Proximity Verifier Core for Android: build/build-your-proximity-verifier/build-your-proximity-verifier-core-for-android.md
          - Build your rQES:
              - Overview: build/build-your-rqes/index.md
              - Build your rQES SDK UI for Android: build/build-your-rqes/build-your-rqes-sdk-ui-for-android.md
              - Build your rQES Core for Android: build/build-your-rqes/build-your-rqes-core-for-android.md
              - Build your rQES SDK UI for iOS: build/build-your-rqes/build-your-rqes-sdk-ui-for-ios.md
              - Build your rQES Kit for iOS:  build/build-your-rqes/build-your-rqes-kit-for-ios.md
          - Supporting Ecosystem Services:
              - Overview: build/supporting-ecosystem-services/index.md
              - RP Registration Service: build/supporting-ecosystem-services/rp-registration-service.md
              - RSSP: build/supporting-ecosystem-services/rssp.md
              - Revocation Service: build/supporting-ecosystem-services/revocation-service.md
              - Trust List Service: build/supporting-ecosystem-services/trusted-list-service.md
      - Test:
          - Introduction: test/index.md
          - Wallet Application:
              - Wallet Application: test/wallet-application/index.md
              - Android: test/wallet-application/android.md
              - iOS: test/wallet-application/ios.md
          - Issuer: test/issuer.md
          - Online Verifier: test/online-verifier.md
          - Proximity Verifier: test/proximity-verifier.md
      - Use Cases:
          - Use Cases: use-cases/index.md
          - Mobile Driving License:
              - Mobile Driving License: use-cases/mobile-driving-license/index.md
              - mDL Solution:
                  - mDL Solution: use-cases/mobile-driving-license/mdl-overview/index.md
                  - Legal Basis: use-cases/mobile-driving-license/mdl-overview/legal-basis.md
                  - Standards and Protocols: use-cases/mobile-driving-license/mdl-overview/standards-and-protocols.md
              - mDL Architecture:
                  - mDL Architecture: use-cases/mobile-driving-license/mdl-architecture/index.md
                  - EUDI Wallet: use-cases/mobile-driving-license/mdl-architecture/eudi-wallet.md
                  - Proximity Verifier: use-cases/mobile-driving-license/mdl-architecture/proximity-verifier.md
                  - Remote Verifier Web: use-cases/mobile-driving-license/mdl-architecture/remote-verifier-web.md
                  - mDL Issuing Authority: use-cases/mobile-driving-license/mdl-architecture/mdl-issuing-authority.md
              - mDL Guides:
                  - Introduction: use-cases/mobile-driving-license/mdl-guides/index.md
                  - Wallet Provider:
                      - Getting Started: use-cases/mobile-driving-license/mdl-guides/wallet-provider/index.md
                      - Wallet Developers Workflow: use-cases/mobile-driving-license/mdl-guides/wallet-provider/wallet-developers-workflow.md
                      - Wallet Provider Specs: use-cases/mobile-driving-license/mdl-guides/wallet-provider/wallet-provider-specs.md
                  - mDL Issuer:
                      - Getting Started: use-cases/mobile-driving-license/mdl-guides/mdl-issuer/index.md
                      - mDL Issuance Workflow: use-cases/mobile-driving-license/mdl-guides/mdl-issuer/mdl-issuance-workflow.md
                      - mDL Issuer Specs: use-cases/mobile-driving-license/mdl-guides/mdl-issuer/mdl-issuer-specs.md
                      - mDL Revocation Specs: use-cases/mobile-driving-license/mdl-guides/mdl-issuer/mdl-revocation-specs.md
                  - mDL Verifier: 
                      - Getting Started: use-cases/mobile-driving-license/mdl-guides/mdl-verifier/index.md
                      - mDL Verifier Workflow: use-cases/mobile-driving-license/mdl-guides/mdl-verifier/mdl-verifier-workflow.md
                      - mDL Reader Specs: use-cases/mobile-driving-license/mdl-guides/mdl-verifier/mdl-reader-specs.md
                      - mDL Remote Verifier Specs: use-cases/mobile-driving-license/mdl-guides/mdl-verifier/mdl-remote-verifier-specs.md

extra:
  version:
    provider: mike
    alias: true

plugins:
  - mike
  - tags
  - privacy
  - social
